namespace: "User"

tasks:
  TaskMonthly:
    name: "Task Monthly"
    schedule_type: "MONTHLY"
    run: "C:\\Windows\\System32\\cmd.exe"
    arguments:
      - "echo Hello"
      - "echo World"
    modifiers: "LASTDAY"
    month: JAN
    start_time: "22:50:10"
    end_time: "23:50:10"
    start_date: "08/23/2023"
    end_date: "09/26/2024"
  
  TaskWeekly:
    name: "Task Weekly"
    schedule_type: "WEEKLY"
    run: "C:\\Windows\\System32\\cmd.exe"
    arguments:
      - "echo Good"
      - "echo Day"
    modifiers: 2
    start_time: "20:50:10"
    end_time: "21:50:10"
    start_date: "08/24/2023"
    end_date: "09/27/2024" 

  TaskDaily:
    name: "Task Daily"
    schedule_type: "DAILY"
    run: "C:\\Windows\\System32\\cmd.exe"
    arguments:
      - "echo Good"
      - "echo Night"
    modifiers: 1
    start_time: "00:00:00"
    end_time: "01:00:00"
    start_date: "08/24/2023"
    end_date: "09/27/2024"
  